### ISSUE TITLE
0 byte reads kill the program

### ISSUE THREAD

**Issue by cnorthway** [accessibility-oscilloscope/signal-processing#2]
This isn't something that should happen on the 'happy path', but if a program writes to the input fifo and exits, the reader will read 0 bytes for EOF. Means doing individual tests with `cat` or similar programs will work once and then blow up the processing stage. 

We handled this elsewhere with a check for read return value == 0 and check for not error (therefore just EOF) and just retry instead of throwing an error.

see https://github.com/accessibility-oscilloscope/ascii-conv/blob/227bdb2e67eb5e11c27ae30a2426a903a0d3d422/ascii-conv.c#L29-L34
and better_read does this implicitly
https://github.com/accessibility-oscilloscope/pnt-lut/blob/6cf316ed9afb41925bdc270cafe98db489440bb6/pnt-lut.c#L29-L36

Downside to this approach is that you can then get the program into a state where it's continually trying to read and using up a bunch of CPU spinning in a loop.

Maybe exiting early is okay? (definitely log in that case)
Maybe the spinning loop is okay? (just have to be aware of it eating CPU, no warning unless the writer logs when it exits)

Maybe there's a better solution?

@jleightcap because I know I talked with him about this before elsewhere

**Comment by jleightcap** [comment]
yeah, good note. can just leave this up to whatever you all find appropriate for the implementation + integration.

the signal processing is semantically the same as the signal compiler, where it doesn't have global 'state', so it can simply restart the program like the signal compiler + `fifo-wrapper`.

or like you mentioned it can be handled internally in this implementation.

either or is fine. the former has the downside of restarting the python interpreter from scratch, but that's infrequent and probably not a huge overhead.

**Comment by nicholasmullikin** [comment]
Hmm i'm realizing there is a bit of difference between the python version and the c versions. It looks like the flags are gonna pose a problem in using the pipe wrapper:
`python3 -u main.py -i $SIGPROC_FIFO -o $SIGCOMP_FIFO` vs `pipe-wrapper signal-compiler /run/signal-compiler /dev/stdout`

**Comment by nicholasmullikin** [comment]
I suppose I could modify either the python program arguments or make a new pipe wrapper

**Comment by jleightcap** [comment]
i think the pipe wrapper should still work, all it does is `eval` a string so you should be able to do whatever you want in there.

`pipe-wrapper "literally whatever you want" [where you want stdin to come from] [where you want stdout to go]`

feel free to pm me i might be misunderstanding

**Comment by nicholasmullikin** [comment]
https://github.com/accessibility-oscilloscope/signal-processing/pull/4
