### ISSUE TITLE
check return values of open calls and log

### ISSUE THREAD

**Issue by cnorthway** [accessibility-oscilloscope/signal-processing#3]
nicer than silently exiting if program is given bad fifos. Can we syslog?

**Comment by nicholasmullikin** [comment]
I think the python will return an error message by default and not just seg fault or something. Looks like we can use https://docs.python.org/3/library/syslog.html though

Testing:
```
pi@pi:~/accessibility-oscilloscope/signal-processing $ python main.py -i test
Traceback (most recent call last):
  File "/home/pi/accessibility-oscilloscope/signal-processing/main.py", line 207, in <module>
    input_fifo = os.open(input_path, os.O_RDONLY)
FileNotFoundError: [Errno 2] No such file or directory: 'test'
```

**Comment by nicholasmullikin** [comment]
Built in which is nice

**Comment by nicholasmullikin** [comment]
https://github.com/accessibility-oscilloscope/signal-processing/pull/5
